language: ruby
bundler_args: --without development
rvm:
    - 1.9.3
    - 2.0.0
    - ruby-head
env:
    - DB=sqlite
matrix:  
  allow_failures:
    - rvm: ruby-head

branches:
    only:
        - master
        - develop
        - /^release.*$/
        - /^hotfix.*$/

before_script:
    - rake db:create
    - rake db:migrate
    - rake db:test:prepare

script: 
    - bundle exec rake jasmine:ci