language: ruby
bundler_args: --without development
rvm:
    - 1.9.3
    - 2.0.0
    - ruby-head
env:
    - DB=sqlite
matrix:  
  allow_failures:
    - rvm: ruby-head

branches:
    only:
        - master
        - develop
        - /^release.*$/
        - /^hotfix.*$/

before_script:
    - rake db:create
    - rake db:migrate
    - rake db:test:prepare
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3 # give xvfb some time to start
    - rackup  # start a Web server
    - sleep 3 # give Web server some time to bind to sockets, etc
	
task :travis do
  ["rspec spec", "rake jasmine:ci"].each do |cmd|
    puts "Starting to run #{cmd}..."
    system("export DISPLAY=:99.0 && bundle exec #{cmd}")
    raise "#{cmd} failed!" unless $?.exitstatus == 0
  end
end